schema_version: 1

context:
  name: lib4sbom
  version: 0.8.4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # There is no sdist on PyPI
  url: https://github.com/anthonyharrison/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: c71b7232c633870a05cac78ee75fbcf4a586e80897d3c4864de6e9d408f0fa32

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - pyyaml >=5.4
    - semantic_version
    - defusedxml

tests:
  - python:
      imports:
        - lib4sbom
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Library to ingest and generate SBOMs
  description: |
    Lib4SBOM is a library to parse and generate Software Bill of Materials (SBOMs). It supports SBOMs created in both SPDX and CycloneDX formats.
  homepage: https://github.com/anthonyharrison/lib4sbom
  repository: https://github.com/anthonyharrison/lib4sbom

extra:
  recipe-maintainers:
    - xhochy
